export const API_ROUTES = {
  AUTH: {
    CHANGE_EMAIL: "/api/auth/change-email",
    VERIFY_EMAIL_CHANGE: "/api/auth/verify-email-change",
    REGISTER: "/api/auth/register",
    LOGIN: "/api/auth/login",
    LOGOUT: "/api/auth/logout",
    ME: "/api/auth/me",
    VERIFY_EMAIL: "/api/auth/verify-email",
    RESEND_VERIFICATION: "/api/auth/resend-verification",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
  },
  PROFILE: {
    ME: "/api/profile/me",
    PUBLIC: "/api/profiles/:username",
    PICTURES: "/api/profile/pictures",
    PICTURE: "/api/profile/pictures/:pictureId",
    MAIN_PICTURE: "/api/profile/pictures/:pictureId/main",
    LOCATION: "/api/profile/location",
    TAGS: "/api/tags",
  },
  BROWSE: { SUGGESTIONS: "/api/profiles/suggestions" },
  SEARCH: { PROFILES: "/api/profiles/search" },
  INTERACTIONS: {
    LIKE: "/api/profiles/:userId/like",
    LIKES_RECEIVED: "/api/interactions/likes-received",
    CONNECTIONS: "/api/interactions/connections",
    VIEW: "/api/profiles/:userId/view",
    VIEWS: "/api/interactions/views",
    BLOCK: "/api/profiles/:userId/block",
    REPORT: "/api/profiles/:userId/report",
  },
  CHAT: {
    CONVERSATIONS: "/api/conversations",
    MESSAGES: "/api/conversations/:userId/messages",
  },
  NOTIFICATIONS: {
    LIST: "/api/notifications",
    UNREAD_COUNT: "/api/notifications/unread-count",
    READ: "/api/notifications/:notificationId/read",
    READ_ALL: "/api/notifications/read-all",
  },
} as const;